### PR TITLE
chore: exclude Alexa::ASK::Skill and REGISTRY::TEST::RESOURCE1::MODULE

### PR DESCRIPTION
**Pull request by corymhall**
excluding Alexa::ASK::Skill since it is already published as
@aws-cdk/alexa-ask

excluding REGISTRY::TEST::RESOURCE1::MODULE since it is a test module

### CODE REVIEW

**Comment by corymhall** [comment]
@eladb not sure what the process should be if we want to exclude a package that has already been published.

**Review by eladb — APPROVED** [review]
I think we'll need to manually delete these directories

**Comment by eladb** [comment]
> @eladb not sure what the process should be if we want to exclude a package that has already been published. 

I believe we need to manually deprecate it from all package managers 😩

Additionally/alternatively we should publish it with deprecation info in the readme and deprecated flag in package.json

So I guess filtering it out is not the right thing. We should add support for deprecations.

**Review by eladb — CHANGES_REQUESTED** [review]
See my note about deprecation

**Comment by corymhall** [comment]
mergify is too fast!

**Pull request merged**
