### PR TITLE
feat: update registry

### PR DESCRIPTION
**Pull request by cgarvis**
Manually update the registry since we haven't done this for a while.

### CODE REVIEW

**Comment by cgarvis** [comment]
`npx projen` fails.

```
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
Alexa::ASK::Skill does not have a LatestPublicVersion
Excluding type TF::Akamai::DnsRecord
  > Unresolvable read-only property (attribute) Aqua::Enterprise::Enforcer.Resources
  > Unresolvable read-only property (attribute) Aqua::Enterprise::KubeEnforcer.Resources
  > Unresolvable read-only property (attribute) Aqua::Enterprise::Scanner.Resources
  > Unresolvable read-only property (attribute) Aqua::Enterprise::Server.Resources
  > Unsupported type {"description":"Resources from the helm charts","type":"object"} for read-only property (attribute) AWSQS::Kubernetes::Helm.Resources
  > Unsupported type {"type":"boolean","description":"Whether this record can be modified/deleted (true means it's managed by Cloudflare)"} for read-only property (attribute) Cloudflare::Dns::Record.Locked
  > Unsupported type {"type":"boolean","description":"Whether the record can be proxied by Cloudflare or not"} for read-only property (attribute) Cloudflare::Dns::Record.Proxiable
  > Unsupported type {"type":"integer"} for read-only property (attribute) Databricks::Clusters::Cluster.LastStateLossTime
  > Unsupported type {"type":"integer"} for read-only property (attribute) Databricks::Clusters::Cluster.LastActivityTime
  > Unsupported type {"type":"integer"} for read-only property (attribute) Databricks::Clusters::Cluster.LastRestartedTime
  > Unsupported type {"type":"boolean"} for read-only property (attribute) Databricks::Clusters::Cluster.InitScriptsSafeMode
  > Unsupported type {"type":"integer"} for read-only property (attribute) Databricks::Clusters::Job.JobId
  > Unsupported type {"type":"integer"} for read-only property (attribute) Databricks::Clusters::Job.CreatedTime
  > Unsupported type {"description":"Whether or not this downtime is currently active","type":"boolean"} for read-only property (attribute) Datadog::Monitors::Downtime.Active
  > Unsupported type {"description":"POSIX Timestamp of cancellation of this downtime (null if not canceled)","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.Canceled
  > Unsupported type {"description":"Id of the user who created this downtime","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.CreatorId
  > Unsupported type {"description":"Type of this downtime","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.DowntimeType
  > Unsupported type {"description":"Id of this downtime","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.Id
  > Unsupported type {"description":"The ID of the parent downtime to this one","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.ParentId
  > Unsupported type {"description":"Id of the user who updated this downtime","type":"integer"} for read-only property (attribute) Datadog::Monitors::Downtime.UpdaterId
  > Unsupported type {"description":"ID of the monitor","type":"integer"} for read-only property (attribute) Datadog::Monitors::Monitor.Id
  > Unresolvable read-only property (attribute) Datadog::Monitors::Monitor.State
  > Unresolvable read-only property (attribute) Datadog::Monitors::Monitor.OverallState
  > Unsupported type {"$ref":"#/definitions/Creator"} for read-only property (attribute) Datadog::Monitors::Monitor.Creator
  > Unresolvable read-only property (attribute) Datadog::SLOs::SLO.State
  > Unresolvable read-only property (attribute) Datadog::SLOs::SLO.OverallState
  > Unsupported type {"$ref":"#/definitions/Creator"} for read-only property (attribute) Datadog::SLOs::SLO.Creator
  > Unsupported type {"$ref":"#/definitions/Id"} for read-only property (attribute) Dynatrace::Configuration::Dashboard.Id
  > Unresolvable read-only property (attribute) Dynatrace::Configuration::Dashboard.Metadata/ClusterVersion
  > Unsupported type {"description":"The SLO is enabled (true) or disabled (false).","type":"boolean"} for read-only property (attribute) Dynatrace::Environment::ServiceLevelObjective.Enabled
  > Unsupported type {"description":"Number of OPEN problems related to the SLO.\n\nHas the value of -1 if there's an error with fetching SLO related problems.","type":"integer"} for read-only property (attribute) Dynatrace::Environment::ServiceLevelObjective.RelatedOpenProblems
  > Unsupported type {"description":"Total number of problems related to the SLO.\n\nHas the value of -1 if there's an error with fetching SLO related problems.","type":"integer"} for read-only property (attribute) Dynatrace::Environment::ServiceLevelObjective.RelatedTotalProblems
  > Unsupported type {"description":"Determines if items in the dictionary are readable or not.","type":"boolean","default":false} for read-only property (attribute) Fastly::Dictionary::Dictionary.WriteOnly
  > Unsupported type {"$ref":"#/definitions/Version"} for read-only property (attribute) Fastly::Services::Backend.Version
  > Unsupported type {"$ref":"#/definitions/CreatedAt"} for read-only property (attribute) Fastly::Services::Backend.CreatedAt
  > Unsupported type {"$ref":"#/definitions/UpdatedAt"} for read-only property (attribute) Fastly::Services::Backend.UpdatedAt
  > Unsupported type {"$ref":"#/definitions/DeletedAt"} for read-only property (attribute) Fastly::Services::Backend.DeletedAt
  > Unsupported type {"$ref":"#/definitions/Name"} for read-only property (attribute) Fastly::Services::Domain.DomainName
  > Unsupported type {"$ref":"#/definitions/Version"} for read-only property (attribute) Fastly::Services::Domain.Version
  > Unsupported type {"$ref":"#/definitions/CreatedAt"} for read-only property (attribute) Fastly::Services::Domain.CreatedAt
  > Unsupported type {"$ref":"#/definitions/UpdatedAt"} for read-only property (attribute) Fastly::Services::Domain.UpdatedAt
  > Unsupported type {"$ref":"#/definitions/DeletedAt"} for read-only property (attribute) Fastly::Services::Domain.DeletedAt
  > Unsupported type {"$ref":"#/definitions/Version"} for read-only property (attribute) Fastly::Services::Healthcheck.Version
  > Unsupported type {"$ref":"#/definitions/CreatedAt"} for read-only property (attribute) Fastly::Services::Healthcheck.CreatedAt
  > Unsupported type {"$ref":"#/definitions/UpdatedAt"} for read-only property (attribute) Fastly::Services::Healthcheck.UpdatedAt
  > Unsupported type {"$ref":"#/definitions/DeletedAt"} for read-only property (attribute) Fastly::Services::Healthcheck.DeletedAt
  > Unsupported type {"$ref":"#/definitions/Id"} for read-only property (attribute) Fastly::Services::Service.Id
  > Unsupported type {"$ref":"#/definitions/Type"} for read-only property (attribute) Fastly::Services::Service.Type
  > Unsupported type {"$ref":"#/definitions/Paused"} for read-only property (attribute) Fastly::Services::Service.Paused
  > Unsupported type {"$ref":"#/definitions/CustomerId"} for read-only property (attribute) Fastly::Services::Service.CustomerId
  > Unsupported type {"$ref":"#/definitions/CreatedAt"} for read-only property (attribute) Fastly::Services::Service.CreatedAt
  > Unsupported type {"$ref":"#/definitions/UpdatedAt"} for read-only property (attribute) Fastly::Services::Service.UpdatedAt
  > Unsupported type {"$ref":"#/definitions/DeletedAt"} for read-only property (attribute) Fastly::Services::Service.DeletedAt
/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:220
        throw new Error('only "string" enums are supported');
              ^
Error: only "string" enums are supported
    at TypeGenerator.emitTypeInternal (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:220:15)
    at TypeGenerator.typeForProperty (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:509:17)
    at TypeGenerator.emitProperty (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:424:31)
    at /Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:396:14
    at typesToEmit.<computed> (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:279:22)
    at TypeGenerator.renderToCode (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/json2jsii/src/type-generator.ts:315:27)
    at CfnResourceGenerator.emitDefinitionTypes (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/cdk-import/src/cfn-resource-generator.ts:99:9)
    at CfnResourceGenerator.render (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/cdk-import/src/cfn-resource-generator.ts:73:10)
    at CloudFormationTypeProject.preSynthesize (/Users/cgarvis/workspace/cdk-cloudformation/projenrc/type-package.ts:316:24)
    at TypeScriptProject.synth (/Users/cgarvis/workspace/cdk-cloudformation/node_modules/projen/src/project.ts:517:12)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /Users/cgarvis/workspace/cdk-cloudformation)
```

**Comment by cgarvis** [comment]
Screen Shot 2023-01-25 at 10 46 53 AM

**Comment by mrgrain** [comment]
> Screenshot

Added some logs, it's actually failing at `GitHub::Repositories::Webhook`

**Comment by mrgrain** [comment]
Closed in favour of #162

**Pull request closed without merging**
